insert into public.exercises (name, description, category, difficulty, equipment_required, restrictions, alternatives, muscle_groups, primary_muscle)
values
  ('Flexiones', 'Empuje horizontal con el peso corporal.', 'compound', 'beginner', '[]', '[]', '["Press banca"]', '["pecho", "triceps"]', 'pectorals'),
  ('Aperturas en polea', 'Aducción horizontal controlada en polea.', 'accessory', 'intermediate', '["cable"]', '["shoulder_injury"]', '["Press banca"]', '["pecho"]', 'pectorals'),
  ('Fondos para pecho', 'Fondos con inclinación para enfatizar pectoral.', 'compound', 'intermediate', '["parallel_bars"]', '["shoulder_injury"]', '["Press banca"]', '["pecho", "triceps"]', 'pectorals'),
  ('Dominadas', 'Tracción vertical con peso corporal.', 'compound', 'intermediate', '["pull_up_bar"]', '[]', '["Jalon al pecho"]', '["espalda", "biceps"]', 'lats'),
  ('Remo sentado en polea', 'Tracción horizontal desde posición sentada.', 'compound', 'beginner', '["cable"]', '["back_injury"]', '["Jalon al pecho"]', '["espalda", "biceps"]', 'lats'),
  ('Jalón de brazos rectos', 'Extensión de hombro en polea para dorsal.', 'accessory', 'beginner', '["cable"]', '[]', '["Jalon al pecho"]', '["espalda"]', 'lats'),
  ('Face pull', 'Tracción hacia la cara para deltoides posterior.', 'accessory', 'beginner', '["cable"]', '["shoulder_injury"]', '["Elevaciones laterales"]', '["hombros"]', 'deltoids'),
  ('Pájaros con mancuernas', 'Apertura posterior tumbado con mancuernas.', 'accessory', 'beginner', '["dumbbell", "bench"]', '["shoulder_injury"]', '["Face pull"]', '["hombros"]', 'deltoids'),
  ('Elevaciones frontales', 'Elevación frontal controlada con mancuernas.', 'accessory', 'beginner', '["dumbbell"]', '["shoulder_injury"]', '["Elevaciones laterales"]', '["hombros"]', 'deltoids'),
  ('Curl con barra', 'Flexión de codo con barra.', 'accessory', 'beginner', '["barbell"]', '["elbow_injury"]', '["Curl de biceps"]', '["biceps"]', 'biceps'),
  ('Curl martillo', 'Flexión de codo con agarre neutro.', 'accessory', 'beginner', '["dumbbell"]', '["elbow_injury"]', '["Curl de biceps"]', '["biceps", "antebrazos"]', 'biceps'),
  ('Curl predicador', 'Flexión de codo apoyado en banco predicador.', 'accessory', 'intermediate', '["ez_bar", "preacher_bench"]', '["elbow_injury"]', '["Curl de biceps"]', '["biceps"]', 'biceps'),
  ('Fondos para tríceps', 'Fondos verticales para extensión de codo.', 'compound', 'intermediate', '["parallel_bars"]', '["shoulder_injury", "elbow_injury"]', '["Extension de triceps en polea"]', '["triceps"]', 'triceps'),
  ('Extensión de tríceps por encima de la cabeza', 'Extensión de codo en polea alta.', 'accessory', 'intermediate', '["cable"]', '["elbow_injury"]', '["Extension de triceps en polea"]', '["triceps"]', 'triceps'),
  ('Extensión de tríceps en polea', 'Extensión de codo con barra en polea.', 'accessory', 'beginner', '["cable"]', '["elbow_injury"]', '["Fondos para triceps"]', '["triceps"]', 'triceps'),
  ('Zancadas con barra', 'Zancada alterna con barra sobre la espalda.', 'compound', 'intermediate', '["barbell"]', '["knee_injury"]', '["Prensa de piernas"]', '["piernas", "gluteos"]', 'quadriceps'),
  ('Extensión de cuádriceps', 'Extensión de rodilla en máquina.', 'accessory', 'beginner', '["machine"]', '["knee_injury"]', '["Prensa de piernas"]', '["piernas"]', 'quadriceps'),
  ('Sentadilla dividida con mancuernas', 'Sentadilla unilateral con mancuernas.', 'compound', 'intermediate', '["dumbbell"]', '["knee_injury"]', '["Sentadilla goblet"]', '["piernas", "gluteos"]', 'quadriceps'),
  ('Buenos días', 'Bisagra de cadera con barra ligera.', 'compound', 'intermediate', '["barbell"]', '["back_injury"]', '["Curl femoral"]', '["isquios", "gluteos"]', 'hamstrings'),
  ('Puente de glúteos con barra', 'Extensión de cadera desde el suelo.', 'compound', 'beginner', '["barbell"]', '[]', '["Hip thrust"]', '["gluteos"]', 'glutes'),
  ('Aducción de cadera en polea', 'Aducción unilateral de cadera en polea.', 'accessory', 'beginner', '["cable"]', '["hip_injury"]', '["Hip thrust"]', '["aductores"]', 'adductors'),
  ('Crunch abdominal', 'Flexión de tronco con peso corporal.', 'core', 'beginner', '[]', '[]', '["Plancha"]', '["core"]', 'core'),
  ('Elevación de piernas colgado', 'Elevación de piernas desde barra.', 'core', 'intermediate', '["pull_up_bar"]', '["back_injury"]', '["Plancha"]', '["core"]', 'core'),
  ('Giros rusos en polea', 'Rotación de tronco con resistencia.', 'core', 'intermediate', '["cable"]', '["back_injury"]', '["Pallof press"]', '["core"]', 'core'),
  ('Crunch en polea', 'Flexión de tronco arrodillado en polea.', 'core', 'beginner', '["cable"]', '["back_injury"]', '["Plancha"]', '["core"]', 'core'),
  ('Hiperextensiones', 'Extensión de tronco en banco romano.', 'accessory', 'beginner', '["hyperextension_bench"]', '["back_injury"]', '["Plancha"]', '["espalda", "gluteos"]', 'lower_back'),
  ('Elevación de gemelos de pie', 'Flexión plantar de pie con peso corporal.', 'accessory', 'beginner', '[]', '[]', '["Elevacion de gemelos sentado"]', '["gemelos"]', 'calves'),
  ('Elevación de gemelos sentado', 'Flexión plantar sentado con barra.', 'accessory', 'beginner', '["barbell", "bench"]', '[]', '["Elevacion de gemelos de pie"]', '["gemelos"]', 'calves')
on conflict (name) do nothing;